name: update-companies
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (`aiohttp`)
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run script
        run: |
          python3 ./src/update-json.py ${{ secrets.GITHUB_TOKEN }}
          python3 ./src/update-markdown.py

      - name: Commit & Push changes
        uses: Andro999b/push@patch-1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: >
            🎉 chore: update draws for ${{ env.DATE }}
